name: flutter_readable
on:
  push:
    branches: [master]
    paths:
      - "flutter_readable/**"
      - ".github/workflows/flutter_readable.yml"
  pull_request:
    branches: [master]
    paths:
      - "flutter_readable/**"
      - ".github/workflows/flutter_readable.yml"
jobs:
  test:
    defaults:
      run:
        working-directory: ./flutter_readable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.4"
          channel: "stable"
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: "flutter_readable/coverage/lcov.info"
